# Generated by Django 5.1 on 2025-09-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
    ]
