# Generated by Django 5.2.5 on 2025-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=0, upload_to='Category_Icons'),
            preserve_default=False,
        ),
    ]
