# Generated by Django 5.2.5 on 2025-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
