# Generated by Django 5.1 on 2025-12-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0003_alter_productmedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/media/'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/media/'),
        ),
    ]
