# Generated by Django 6.0 on 2025-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0004_productmedia_video_file_productmedia_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Category_Icons'),
        ),
    ]
