# Generated by Django 5.1 on 2025-12-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='video_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='video_file',
        ),
    ]
